### PR TITLE
Update to 1.18.2, closes #10

### LINKED ISSUE #10: [Enhancement] 1.18.2 lacks diagonal fences
It seems like as of now there are no diagonal fence mods for 1.18.x

Sorry if it's a bother, but i'm sure you can point all the people begging for ports here if they bother you.

### PR DESCRIPTION
**Pull request by XFactHD**
I've fallen in love with this mod ever since I added support for it in FramedBlocks. I really miss the mod in my current 1.18 playthrough, so I thought I would try to be helpful and do a basic port of Diagonal Fences to 1.18.2.
Closes #10 

A summary of the changes I did apart from adapting to the new MC code:

- Update the Gradle wrapper and FG
- Fix the build.gradle to be compatible with the above (remove jcenter, use the new cursemaven, fix signJar task, fix dependencies, update Mixin processor)
- Move to Parchment mappings as MCP mappings are not available anymore
- Rename a few classes to better fit the official names (some of them appear as file deletions due to heavy changes of their code)
- Remove references to the seemingly removed "Element" system from PuzzlesLib
- Fix a few unexpected Mixin errors, mostly caused by to the Java version bump

I have tried to stay as close to your initial code style as possible.
I have also not done any major changes to the implementation as it is still fully functional the way you wrote it initially.
I have tested the mod in singleplayer and on a dedicated server and everything works perfectly fine as far as I can tell.

If there is anything I should fix or change, please let me know.

I have created this as a draft because the target branch is wrong. I'll mark it as ready when you decided if you are interested in this PR and made a 1.18 branch that I can target.

### CODE REVIEW

**Comment by Fuzss** [comment]
Wow, that's amazing! I can't believe how well you've been able to adapt to my code style for 1.17+.

I've actually held back on porting the mod since I was inspired by your mod and was planning to overhaul the model generation system to directly manipulate quads just like you without the need for creating those fake resources, so what a coincidence.
I'm also planning to address a few more problems with the mod, mainly that adding new block states is a terrible idea and breaks a lot of things, even vanilla things such as feature generation (this is fixed in the mod, but it's really just a hack). So there doesn't really seem to be a way around adding new dedicated diagonal fence blocks (although the user shouldn't notice this at all, this would only be on the technical implementation side). Not sure yet though if having a new block for every fence block or just a single block with a block entity is a better idea...

But since the port is done now, I'm happy to accept the PR and postpone my plans even further :D
I've now created a new default branch for 1.18. Thanks a lot for your effort!

**Comment by XFactHD** [comment]
> planning to overhaul the model generation system to directly manipulate quads

Interesting, that's going to be a challenge because you may not be able to just create quads out of nothing like I am because you can't be sure that the existing arms of the fence use the same texture coordinates you would end up on the generated arms.
There may be ways to do something similar to what you are doing now (cloning and rotating the existing arms) but within the baked model. I'll think about it in the coming days.
If one of us can get something like this working, then it should be possible to do ship this as an update after the initial release.

> adding new dedicated diagonal fence blocks (although the user shouldn't notice this at all, this would only be on the technical implementation side)

That may be fairly easy to do with one or two Mixin injects and a new block, atleast for normal fences. Creation of a new diagonal fence block per existing fence block won't be possible because you can't determine the set of existing fences at the time you need to create the diagonal fences. Using a BlockEntity for this (basically like I am doing for the camo) would be an option.
The only problem I already see with this is that FramedBlocks support would not be possible anymore, except if I basically reimplement the whole logic in FramedBlocks. I could extend the API to allow other mods to create fences that use your logic but circumvent the replacement and storage in a BlockEntity. I have some ideas how that could work.
If you want, I could try rewriting this to be based on a separate block. I have some free time on the weekend where I could do that.

> I've now created a new default branch for 1.18

I've updated the target branch and marked the PR ready for review, so it's ready to go if you want to pull it as-is.

**Comment by Fuzss** [comment]
Yeah doing the cloning and rotating part within the baked model is what I meant. The problem with the current implementation comes down to limitations with vanilla's unbaked models, since they don't allow for rotating on more than one axis at once. So since I need to rotate parts on y any rotations on x and z would be overridden. I'm currently just skipping parts that have such rotations, but this is not ideal.

For the new block/block entity thing, I haven't made up my mind about that. Especially with a block entity I'm quite concerned with performance, although it would be a much nicer implementation than many separate blocks. For separate blocks though my idea was to do it like MrCrayfish's furniture mod addon where he just manually added new blocks for other mods. Although maintaining such an implementation really is no fun at all, so the block entity solution is far more likely. 

You don't need to work on these ideas, I mainly wanted to outline my plans as a future reference for when I come back to the mod. But sure if you want to help I'm happy to accept that.

And thanks again for the PR, I'll accept it later.

**Comment by XFactHD** [comment]
> Yeah doing the cloning and rotating part within the baked model is what I meant.

Took a look at this because I was curious. Turns out that this is fairly trivial because the `MultiPartBakedModel` used by fences allows you to get the model for each arm separately with a few tricks and rotate its quads like I do in FramedBlocks.

> manually added new blocks for other mods

That would definitely be a clean, even though slightly annoying, solution. You could even go the way Ceiling Torches went and add a simple plugin system where other mods can register their own diagonal fence blocks for their fences if you haven't added native support for that mod. That way you allow other mods to take some of the burden off your shoulders while still being able to keep an eye on the set of diagonal fence blocks that were registered and need to (potentially) be handled by your model system.

> the block entity solution is far more likely

My approach for this would be to have a block that handles all the logic and uses your special BlockEntity for storing the fence type and a model that handles generation and caching of the models for each state. Another mod with special needs (like FramedBlocks) can then extend this block to add their own special sauce, replace the BlockEntity if needed and then either register a custom model or your default one. The default behaviour would then be to replace standard fences with your special fence under certain circumstances (most likely need a mixin for this) and the custom fences registered by other mods would always use the extended fence block. This avoids needing to decide whether a standard fence has to be replaced with your "default" special fence or with a custom special fence from another mod.

Btw., if you want to discuss this further in a different place, feel free to ping me on the Forge Discord or shoot me DM on Discord.

As a side-note: I only changed the major version of the mod version in the gradle.properties kept the minor and patch the same. This was probably not a good idea in hindsight. I'll leave it that way for you to decide on the versioning though.

**Comment by XFactHD** [comment]
Found an issue while testing something different: the added states don't persist, the fences lose their diagonal connections after relogging.

EDIT: it turns out that the codec you are modifying in the `FenceBlock` Mixin is now used in the `ChunkSerializer` to save the blockstates. Removing that codec replacement fixes the persistence issue. I need to test if this works properly with structures though.

EDIT again: removing the codec modification seems to not create any issues with structures (tested with nether fortress). Can you remember what kinds of issues you had with the added properties and structures?
Loading an NBT structure (created in a different workspace without DiagonalFences) through the structure block also works fine.

**Comment by XFactHD** [comment]
I have now looked a bit deeper into this and spoken to TelepathicGrunt, the resident worldgen expert, and as it turns out that codec hackery is not needed anymore because Mojang changed the BlockState codec to fill in missing properties with default values. Nuking the codec stuff will make this a lot cleaner.

**Comment by XFactHD** [comment]
I have done some production tests in a modpack with fences from Vanilla (obviously), Biomes O' Plenty, Botania, Framed Blocks, Immersive Engineering and Macaw's Fences and Walls.

With the runtime resource pack, everything except FramedBlocks (to be expected) and the Wired Fences from Macaw's Fences and Walls (missing razor wire on the diagonal connections) works fine.
I also tested it with my first implementation of modified baked models and in that test FramedBlocks didn't work (also to be expected) but the Wired Fences from Macaw's Fences and Walls and everything else worked fine.

If you want, I can make a PR for the model transformation system, though I think it should be separate from this one because it makes it easier to view the changes when they are not mixed with the existing structure and naming changes.

**Comment by XFactHD** [comment]
Decided to try this PR in a backup of an actual world I play on and it's glorious. The build I used does include the modified model generation, which is not included in this PR as mentioned before.

I have not found any more issues in my tests. From my point of view this PR is now ready for production.

**Pull request merged**
